name: Generate Changelog

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  gen-changelog:
    runs-on: ubuntu-latest
    environment: genlog_gen_token_trifa
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: install pkgs
      run:  |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update && sudo apt install -y zip grep sudo ruby rubygems git ssh ruby-dev gcc make
            sudo $(which gem) install specific_install

    - name: install github-changelog-generator
      run:  |
            git clone https://github.com/github-changelog-generator/github-changelog-generator -b v1.16.4
            cd github-changelog-generator/
            sudo $(which gem) build github_changelog_generator.gemspec
            sudo $(which gem) install -N github_changelog_generator-1.16.4.gem

    - name: run github-changelog-generator
      env:
            CHANGELOG_GEN_TOKEN: ${{ secrets.CHANGELOG_GEN_TOKEN }}

# --exclude-tags "$(git tag -l 'trifajni*'| tr '\n' ',')" \

      run:  |
            pwd
            $(which ruby) $(which github_changelog_generator) -u zoff99 -p ToxAndroidRefImpl \
            --exclude-tags "$(git tag -l 'trifajni*'| tr '\n' ',')nightly" \
               --token "$CHANGELOG_GEN_TOKEN"

    - name: chmod
      run:  |
            sudo chmod a+r /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/CHANGELOG.md
            ls -rattlh

    - name: upload Changelog file
      uses: actions/upload-artifact@v4
      with:
        name: Changelog
        path: |
          /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/CHANGELOG.md

